server:
  port: 8080
#datasource and database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: paul
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  #turn off the web server, pass none below instead of default
  main:
    web-application-type: servlet